### ISSUE TITLE
Move to npx executable

### ISSUE THREAD

**Issue by Cadienvan** [JointlyTech/spyone#1]
We should move the current script into the bin folder and make it callable via `npx`, as this should bring a nice DX.
The only consideration is about the JSON output. Where should we put it?

**Comment by sumitshinde-84** [comment]
When making a script callable via npx, it is typically a good practice to place the script in the node_modules/.bin directory. This directory is automatically added to the PATH by npm, allowing scripts to be executed with a simple command.

Regarding the JSON output, it really depends on the purpose of the script and the intended use case. If the JSON output is intended to be consumed by another script or program, it might make sense to write it to stdout so that it can be piped to another process. On the other hand, if the JSON output is intended to be read by a human, it might be better to write it to a file and output the path to the file as part of the script's console output.
Ultimately, the decision of where to put the JSON output depends on the specific requirements of the script and how it will be used.

**Comment by Cadienvan** [comment]
Hi @sumitshinde-84, thanks for the summary, do you wanna try to give it a shot and propose a PR? I'd love to review it!

**Comment by sumitshinde-84** [comment]
Apologies @Cadienvan, currently busy with job search. Would love to contribute to your project when time allows. Thanks for understanding.
